a = input('enter the first number: ')
b = input('enter the second number: ')
a = int(a)
b = int(b)

print(str(a),'+', str(b), '=', a+b)
print(str(a),'-', str(b), '=', a-b)
print(str(a),'*', str(b), '=', a*b)
print(str(a),'/', str(b), '=', a/b)
print(str(a),'%', str(b), '=', a%b)
print(str(a),'**', str(b), '=', a**b)
print(str(a),'//', str(b), '=', a//b)